DATASET:
    train_list: ['Human36M', 'COCO', 'MuCo']
    test_list: ['PW3D']
    input_joint_set: 'coco'
    target_joint_set: 'human36'
    workers: 16
    use_gt_input: False

MODEL:
    name: 'pose2mesh_net'
    input_shape: [384, 288]
    normal_loss_weight: 0.1
    edge_loss_weight: 20
    joint_loss_weight: 0.001
    posenet_pretrained: False

TRAIN:
    print_freq: 10
    batch_size: 128
    shuffle: True
    begin_epoch: 1
    end_epoch: 15
    edge_loss_start: 7
    scheduler: 'step'
    lr: 0.001
    lr_step: [12]
    lr_factor: 0.1
    optimizer: 'rmsprop'

AUG:
    flip: False
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False
    weight_path: './experiment/pose2mesh_cocoJ_train_human36_coco_muco/final.pth.tar'
    vis: False
